name: Deploy to Azure Container Apps

on:
  workflow_dispatch:
  push:
    branches:
      - main  # Runs when code is pushed to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      # Note: ACR names must be lowercase. If your registry was created as "DevOpenWebUI",
      # it is normalized to "devopenwebui.azurecr.io".
      AZURE_CONTAINER_REGISTRY: DevOpenWebUI
      CONTAINER_APP_NAME: dev-open-webui
      RESOURCE_GROUP: dev-stage

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Log in to Azure Container Registry (ACR)
      - name: Log in to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io
          username: ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}

      # Step 3: Build and Push Docker Image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_APP_NAME }}:${{ github.sha }}

      # Step 4: Azure Login
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          # Example for creating the service principal:
          # az ad sp create-for-rbac --name "DevOpenWebUI" --role contributor --scopes /subscriptions/<subscription-id>/resourceGroups/dev-stage --sdk-auth

      # Step 5: Deploy to Azure Container Apps
      - name: Deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: .
          registryUrl: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io
          registryUsername: ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}
          containerAppName: ${{ env.CONTAINER_APP_NAME }}
          resourceGroup: ${{ env.RESOURCE_GROUP }}
          imageToBuild: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_APP_NAME }}:${{ github.sha }}
          environmentVariables: OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
