name: Deploy to Azure Container Apps

on:
  workflow_dispatch:
  push:
    branches:
      - main  # Runs when code is pushed to the main branch

permissions:
  contents: write  # ✅ Grants write permissions for creating releases

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      AZURE_CONTAINER_REGISTRY: DevOpenWebUI
      CONTAINER_APP_NAME: dev-open-webui
      RESOURCE_GROUP: dev-stage

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to ACR
        uses: azure/docker-login@v3
        with:
          registry: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io
          username: ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_APP_NAME }}:${{ github.sha }}

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container Apps
        uses: azure/container-app-deploy-action@v1
        with:
          imageToDeploy: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_APP_NAME }}:${{ github.sha }}
          resourceGroup: ${{ env.RESOURCE_GROUP }}
          containerAppName: ${{ env.CONTAINER_APP_NAME }}
          environmentVariables: |
            OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}

      # ✅ Step: Create GitHub Release (Fix)
      - name: Create GitHub Release
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.TOKEN }} # Github Token
          script: |
            const changelog = `## [0.5.16] - 2025-02-20
            
            ### Fixed
            
            - **🔍 Web Search Retrieval Restored**: Resolved a critical issue that broke web search retrieval by reverting deduplication changes, ensuring complete and accurate search results once again.`;

            const release = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: `v0.5.16`,
              name: `v0.5.16`,
              body: changelog,
              draft: false,
              prerelease: false
            });

            console.log(`Created release ${release.data.html_url}`);
